"""Write a chapter's computed values in the form the book reads.

    from _values import Values
    v = Values("ch06")
    v.num("steps.apart", 34)            # \\pyval{ch06.steps.apart}{34}
    v.num("lambda", 0.693147, ".3f")    # \\pyval{ch06.lambda}{0.693}
    v.text("machine", "x86_64")         # \\pyvaltext{...}{x86\\_64}
    v.write()                                  # figures/values/ch06.tex

The page reads \\val{ch06.steps.apart}. A float MUST come with a format:
the number of digits printed is a decision, and a default repr would print
digits no measurement supports. Keys are namespaced by chapter so two
chapters cannot collide.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

CODE = Path(__file__).resolve().parents[1]
OUT = CODE.parent / "figures" / "values"

_TEX = {"\\": r"\textbackslash{}", "_": r"\_", "%": r"\%", "&": r"\&",
        "#": r"\#", "$": r"\$", "{": r"\{", "}": r"\}", "~": r"\~{}",
        "^": r"\^{}"}


def tex(s: str) -> str:
    """Escape a text value so it reaches the page as the characters it is."""
    return "".join(_TEX.get(ch, ch) for ch in s)


class Values:
    def __init__(self, chapter: str) -> None:
        self.chapter = chapter
        self.lines: list[str] = []
        self.keys: set[str] = set()

    def _key(self, key: str) -> str:
        full = f"{self.chapter}.{key}"
        if full in self.keys:
            raise ValueError(f"{full} emitted twice")
        self.keys.add(full)
        return full

    def num(self, key: str, value: float, fmt: str | None = None) -> str:
        """Emit a number. Integers need no format; floats always do."""
        if isinstance(value, float):
            if fmt is None:
                raise ValueError(f"{key}: a float needs a format")
            if not math.isfinite(value):
                raise ValueError(f"{key}: {value} is not a number")
            body = format(value, fmt)
        else:
            body = str(value) if fmt is None else format(value, fmt)
        self.lines.append(f"\\pyval{{{self._key(key)}}}{{{body}}}")
        return body

    def text(self, key: str, value: str) -> str:
        self.lines.append(f"\\pyvaltext{{{self._key(key)}}}{{{tex(value)}}}")
        return value

    def write(self) -> Path:
        OUT.mkdir(parents=True, exist_ok=True)
        path = OUT / f"{self.chapter}.tex"
        script = Path(sys.argv[0]).name
        head = f"% Generated by code/measure/{script} --- do not edit.\n"
        path.write_text(head + "\n".join(self.lines) + "\n", encoding="utf8")
        print(f"  values:  {path.relative_to(CODE.parent)} "
              f"({len(self.lines)} values)")
        return path
