.PHONY: all en pl check source numbers plots diagrams verify code starters \
        debt clean chapter site

# One paper format, two languages: main-en.tex and main-pl.tex differ in two
# lines and share everything else.
LANGS := en pl

UV ?= uv
MMDC ?= $(shell command -v mmdc 2>/dev/null || echo "npx -y @mermaid-js/mermaid-cli@11")
MMD_SRC := $(wildcard figures/mermaid/en/*.mmd) $(wildcard figures/mermaid/pl/*.mmd)
MMD_PDF := $(patsubst figures/mermaid/%.mmd,figures/diagrams/%.pdf,$(MMD_SRC))

# Everything a script under code/measure/ writes and git tracks. The promise
# that the page cannot disagree with its script is exactly as wide as this
# variable and no wider.
COMPUTED := figures/values figures/transcripts

# Headless Chromium for the Mermaid renderer. Override BROWSER if yours lives
# somewhere else.
BROWSER ?= $(shell command -v chromium 2>/dev/null || command -v chromium-browser 2>/dev/null || ls /opt/pw-browsers/chromium-*/chrome-linux/chrome 2>/dev/null | head -1)

all: source numbers plots diagrams en pl check

# ---------------------------------------------------------------------------
# The SOURCE gates read the source and need no PDF, so they run first: they
# cost seconds against a build that costs minutes. parity.py's output is
# captured rather than piped into tail, because a pipeline's exit status is
# the last command's and `parity.py | tail` could never fail.
# ---------------------------------------------------------------------------
source:
	@python3 tools/gen_stubs.py --check
	@out=$$(python3 tools/parity.py) || { echo "$$out"; exit 1; }; \
	 echo "$$out" | tail -n 1
	@python3 tools/check_structure.py --all

check: source
	@python3 tools/checklog.py main-en.log main-pl.log
	@if [ -f main-en.aux ] && [ -f main-pl.aux ]; then python3 tools/reflist.py; \
	 else echo "  (cross-reference comparison skipped: build both editions first)"; fi

en: numbers
	latexmk -pdf -interaction=nonstopmode -file-line-error main-en.tex
	@python3 tools/checklog.py main-en.log

pl: numbers
	latexmk -pdf -interaction=nonstopmode -file-line-error main-pl.tex
	@python3 tools/checklog.py main-pl.log

# One chapter on its own, in its own build directory, for writing it:
#     make chapter CH=ch05          (both languages)
#     make chapter CH=ch05 LANG=pl
chapter:
	@python3 tools/build_chapter.py $(CH) $(if $(LANG),$(LANG),en pl)

clean:
	for j in main-en main-pl; do latexmk -C $$j.tex; done
	rm -rf _build _site
	rm -f *.lab *.plt *.dgm *.ilg *.ind *.idx chapters/*/*.aux appendices/*/*.aux

# ---------------------------------------------------------------------------
# The code. Every listing, lab, measurement and plot is one uv project under
# code/, locked to the versions on the copyright page.
# ---------------------------------------------------------------------------
code:
	cd code && $(UV) sync --locked
	cd code && $(UV) run ruff check .
	cd code && CHAOS_SOLUTIONS=1 $(UV) run pytest

# Every lab STARTER must still fail its test: a lab whose starter already
# passes is not a lab.
starters:
	cd code && CHAOS_STARTERS=fail $(UV) run pytest labs

# ---------------------------------------------------------------------------
# Numbers: every measured value and every quoted output. The book does not
# contain the digits, it contains a reference to them.
# ---------------------------------------------------------------------------
numbers:
	@mkdir -p $(COMPUTED)
	@cd code && for f in measure/*.py; do \
	  case "$$(basename $$f)" in _*) continue;; esac; \
	  echo "  measure: $$f"; \
	  $(UV) run python "$$f" || exit 1; \
	done
	@{ echo '% Generated by `make numbers` --- do not edit.'; \
	   for v in figures/values/*.tex; do \
	     case "$$v" in */all.tex) continue;; esac; \
	     echo "\\input{$${v%.tex}}"; \
	   done; } > figures/values/all.tex

# Fails on drift in a tracked file AND on a file git has never seen, which
# has therefore never been compared to anything. Staged counts as current.
verify: numbers
	@drift=$$(git diff --name-only -- $(COMPUTED)); \
	 new=$$(git ls-files --others --exclude-standard -- $(COMPUTED)); \
	 if [ -n "$$drift" ] || [ -n "$$new" ]; then \
	   [ -n "$$drift" ] && { echo "STALE: these no longer match their script:"; echo "$$drift"; }; \
	   [ -n "$$new" ] && { echo "UNTRACKED (git add them):"; echo "$$new"; }; \
	   exit 1; \
	 else echo "All computed output is current: values and transcripts."; fi

# ---------------------------------------------------------------------------
# Plots and diagrams. Sources are committed; renders are build output.
# ---------------------------------------------------------------------------
plots:
	@cd code && for f in plots/ch*.py; do \
	  $(UV) run python "$$f" || exit 1; \
	done

diagrams: $(MMD_PDF)

figures/diagrams/%.pdf: figures/mermaid/%.mmd figures/mermaid/config.json figures/mermaid/.puppeteer.json
	@mkdir -p $(dir $@)
	$(MMDC) -i $< -o $@ -p figures/mermaid/.puppeteer.json \
	  -c figures/mermaid/config.json -b transparent --pdfFit -w 1600

figures/mermaid/.puppeteer.json:
	@printf '{"executablePath":"%s","args":["--no-sandbox","--disable-dev-shm-usage"]}\n' "$(BROWSER)" > $@

# ---------------------------------------------------------------------------
# Debt: each ledger is a promise made to a reader that is counted rather
# than remembered.
# ---------------------------------------------------------------------------
debt:
	@echo "== Stubs =="; python3 tools/check_structure.py --stubs --soft
	@echo; python3 tools/check_structure.py --all --soft
	@echo; echo "== Polish/English parity =="; python3 tools/parity.py | tail -n 1
	@printf "\n== verifybox blocks per edition: "; \
	 grep -c 'begin{verifybox}' chapters/en/*.tex | awk -F: '{s+=$$2} END {print s+0}'

site: en pl
	@mkdir -p _site
	@cp main-en.pdf "_site/Chaos-from-Zero.pdf"
	@cp main-pl.pdf "_site/Chaos-od-zera.pdf"
	@cp docs/index.html _site/index.html
	@echo "  _site/ assembled."
