#!/usr/bin/env python3
"""Generate Appendix B and notes/02-traps.md from notes/traps/chNN.json.

    python3 tools/gen_traps.py            # write both appendices and the notes
    python3 tools/gen_traps.py --check    # fail if any of them is stale

Each chapter records its misreadings in notes/traps/chNN.json -- the habit in
the reader's own voice, what is true instead, and the section that elicits
it -- in both languages. One file per chapter, because the chapters were
written in parallel and a single shared catalogue is exactly the file several
writers append to at once. Chapter N numbers its entries from 10*N + 1, so no
two chapters can ever allocate the same number.

Appendix B is therefore generated, never typed, and `check_structure.py
--traps` compares it with the catalogue this script also writes.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRAPS = ROOT / "notes" / "traps"

HEAD = {
    "en": {
        "title": "Misreadings of chaos",
        "chapter": "Chapter",
        "intro": (
            "Every misreading the book sets out to correct, in the order the "
            "chapters elicit them. Each is written in the voice of somebody "
            "who believes it, followed by what is true instead and the "
            "section where the book lets you walk into it first. If you "
            "arrived here before reading that section, the entry will make "
            "more sense after it: the point of each trap was to be caught by "
            "it."),
    },
    "pl": {
        "title": "Błędne odczytania chaosu",
        "chapter": "Rozdział",
        "intro": (
            "Każde błędne odczytanie, które książka stara się poprawić, w "
            "kolejności, w jakiej wywołują je rozdziały. Każde jest zapisane "
            "głosem kogoś, kto w nie wierzy, a po nim następuje to, co jest "
            "prawdą, i podrozdział, w którym książka pozwala ci najpierw w nie "
            "wpaść. Jeśli trafiłeś tu przed przeczytaniem tego podrozdziału, "
            "wpis nabierze sensu później: każda pułapka miała na ciebie "
            "zadziałać."),
    },
}


def load() -> tuple[dict, list[tuple[dict, list[dict]]]]:
    m = json.loads((ROOT / "tools" / "chapters.json").read_text(encoding="utf8"))
    out = []
    for c in m["chapters"]:
        p = TRAPS / f"{c['key']}.json"
        if not p.is_file():
            continue
        entries = json.loads(p.read_text(encoding="utf8"))
        base = 10 * int(c["id"])
        for e in entries:
            n = int(e["n"])
            if not base < n < base + 10:
                raise SystemExit(f"{p.name}: trap {n} is outside Chapter "
                                 f"{c['id']}'s block {base + 1}-{base + 9}")
            for lang in ("en", "pl"):
                if not e.get(lang, {}).get("habit") or not e[lang].get("truth"):
                    raise SystemExit(f"{p.name}: trap {n} lacks {lang} text")
        out.append((c, sorted(entries, key=lambda e: int(e["n"]))))
    return m, out


def appendix(lang: str, data: list[tuple[dict, list[dict]]]) -> str:
    h = HEAD[lang]
    lines = [
        f"%% appB --- {h['title']}",
        "%%",
        "%% GENERATED by tools/gen_traps.py from notes/traps/chNN.json. Edit the",
        "%% chapter's JSON, not this file; `make traps` rewrites it and",
        "%% `check_structure.py --traps` checks it against the catalogue.",
        "",
        f"\\chapter{{{h['title']}}}",
        "\\label{app:misreadings}",
        "",
        "\\noindent",
        h["intro"],
        "",
    ]
    for c, entries in data:
        lines.append(f"\\trapchapter{{{h['chapter']}~\\ref{{{c['label']}}}}}"
                     f"{{{c[lang]}}}")
        for e in entries:
            lines.append(f"\\trapentry{{{e['n']}}}{{{e[lang]['habit']}}}%")
            lines.append(f"  {{{e[lang]['truth']}}}%")
            lines.append(f"  {{\\ref{{{e['label']}}}}}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def catalogue(data: list[tuple[dict, list[dict]]]) -> str:
    out = [
        "# Misreadings: the trap catalogue",
        "",
        "GENERATED by `tools/gen_traps.py` from `notes/traps/chNN.json`. Edit",
        "the chapter's JSON, not this file.",
        "",
        "Each chapter owns a block of ten numbers: Chapter N numbers its",
        "entries from 10N + 1. A number is never reused, so a retired entry",
        "leaves a gap. Appendix B prints every entry, in both editions, and",
        "`python3 tools/check_structure.py --traps` fails when the two",
        "disagree.",
        "",
        "| # | Where | The habit | What is true instead |",
        "|---|---|---|---|",
    ]
    for c, entries in data:
        for e in entries:
            habit = e["en"]["habit"].replace("|", "\\|")
            truth = e["en"]["truth"].replace("|", "\\|")
            out.append(f"| {e['n']} | Ch. {c['id']} `{e['label']}` | "
                       f"{habit} | {truth} |")
    return "\n".join(out) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    _, data = load()
    targets = {ROOT / "notes" / "02-traps.md": catalogue(data)}
    for lang in ("en", "pl"):
        targets[ROOT / "appendices" / lang / "appB-misreadings.tex"] = appendix(lang, data)
    stale = []
    for path, text in targets.items():
        old = path.read_text(encoding="utf8") if path.is_file() else ""
        if old != text:
            stale.append(path.relative_to(ROOT))
            if not check:
                path.write_text(text, encoding="utf8")
    n = sum(len(e) for _, e in data)
    if check and stale:
        for s in stale:
            print(f"  OUT OF DATE: {s}  (run python3 tools/gen_traps.py)")
        return 1
    print(f"  {n} misreadings from {len(data)} chapters; "
          f"{'current' if not stale else 'written: ' + ', '.join(map(str, stale))}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
